// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "PluginHandler.h"


PluginIf * PluginHandler::createPlugin()
{
    return new PluginHandler();
}

void PluginHandler::destroyPlugin(PluginIf *p)
{
    delete p;
}

