// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Plugin.h"

class PluginHandler : virtual public PluginIf {
 public:
  PluginHandler() {
    // Your initialization goes here
  }

  void initialize() {
    // Your implementation goes here
    printf("initialize\n");
  }

  void prepareForStart() {
    // Your implementation goes here
    printf("prepareForStart\n");
  }

  void start() {
    // Your implementation goes here
    printf("start\n");
  }

  void active() {
    // Your implementation goes here
    printf("active\n");
  }

  void passive() {
    // Your implementation goes here
    printf("passive\n");
  }

  void prepareForStop() {
    // Your implementation goes here
    printf("prepareForStop\n");
  }

  void stop() {
    // Your implementation goes here
    printf("stop\n");
  }

  void destroy() {
    // Your implementation goes here
    printf("destroy\n");
  }

  static PluginIf * createPlugin();
  static void destroyPlugin(PluginIf *);
};

