/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PluginManagerServant_CONSTANTS_H
#define PluginManagerServant_CONSTANTS_H

#include "PluginManagerServant_types.h"



class PluginManagerServantConstants {
 public:
  PluginManagerServantConstants();

};

extern const PluginManagerServantConstants g_PluginManagerServant_constants;



#endif
