/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PluginServant_CONSTANTS_H
#define PluginServant_CONSTANTS_H

#include "PluginServant_types.h"



class PluginServantConstants {
 public:
  PluginServantConstants();

};

extern const PluginServantConstants g_PluginServant_constants;



#endif
